services:
  # Backend API Service
  - type: web
    name: hrms-backend
    runtime: docker
    plan: free
    dockerfilePath: ./python_backend/Dockerfile
    dockerContext: ./python_backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hrms-db
          property: connectionString
      - key: REDIS_URL
        sync: false
      - key: REDIS_ENABLED
        value: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        value: '["*"]'

  # Frontend React App
  - type: web
    name: hrms-frontend
    runtime: static
    plan: free
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://hrms-backend.onrender.com/api/v1

databases:
  - name: hrms-db
    plan: free
    databaseName: hr_system
    user: hr_user
