# Kong API Gateway Configuration
# Declarative configuration for routing and policies

_format_version: "3.0"
_transform: true

# ==========================================
# Upstream Services
# ==========================================

upstreams:
  - name: auth-service-upstream
    algorithm: round-robin
    targets:
      - target: auth-service:3001
        weight: 100
    healthchecks:
      active:
        healthy:
          interval: 10
          successes: 2
        unhealthy:
          interval: 10
          http_failures: 3

  - name: employee-service-upstream
    algorithm: round-robin
    targets:
      - target: employee-service:3002
        weight: 100
    healthchecks:
      active:
        healthy:
          interval: 10
          successes: 2
        unhealthy:
          interval: 10
          http_failures: 3

  - name: attendance-service-upstream
    algorithm: round-robin
    targets:
      - target: attendance-service:3003
        weight: 100
    healthchecks:
      active:
        healthy:
          interval: 10
          successes: 2
        unhealthy:
          interval: 10
          http_failures: 3

  - name: leave-service-upstream
    algorithm: round-robin
    targets:
      - target: leave-service:3004
        weight: 100
    healthchecks:
      active:
        healthy:
          interval: 10
          successes: 2
        unhealthy:
          interval: 10
          http_failures: 3

  - name: payroll-service-upstream
    algorithm: round-robin
    targets:
      - target: payroll-service:3005
        weight: 100
    healthchecks:
      active:
        healthy:
          interval: 10
          successes: 2
        unhealthy:
          interval: 10
          http_failures: 3

  - name: notification-service-upstream
    algorithm: round-robin
    targets:
      - target: notification-service:3006
        weight: 100
    healthchecks:
      active:
        healthy:
          interval: 10
          successes: 2
        unhealthy:
          interval: 10
          http_failures: 3

# ==========================================
# Services and Routes
# ==========================================

services:
  # Authentication Service
  - name: auth-service
    url: http://auth-service-upstream
    protocol: http
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    routes:
      - name: auth-routes
        paths:
          - /api/v1/auth
        strip_path: false
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Authorization
            - Content-Type
          exposed_headers:
            - X-Auth-Token
          credentials: true
          max_age: 3600
      - name: rate-limiting
        config:
          minute: 60
          policy: local
      - name: request-size-limiting
        config:
          allowed_payload_size: 10
      - name: prometheus

  # Employee Service
  - name: employee-service
    url: http://employee-service-upstream
    protocol: http
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    routes:
      - name: employee-routes
        paths:
          - /api/v1/employees
          - /api/v1/departments
          - /api/v1/designations
        strip_path: false
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          credentials: true
      - name: jwt
        config:
          claims_to_verify:
            - exp
      - name: rate-limiting
        config:
          minute: 100
          policy: local
      - name: prometheus
      - name: request-transformer
        config:
          add:
            headers:
              - X-Service:employee-service

  # Attendance Service
  - name: attendance-service
    url: http://attendance-service-upstream
    protocol: http
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    routes:
      - name: attendance-routes
        paths:
          - /api/v1/attendance
          - /api/v1/shifts
        strip_path: false
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          credentials: true
      - name: jwt
        config:
          claims_to_verify:
            - exp
      - name: rate-limiting
        config:
          minute: 200
          policy: local
      - name: prometheus

  # Leave Service
  - name: leave-service
    url: http://leave-service-upstream
    protocol: http
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    routes:
      - name: leave-routes
        paths:
          - /api/v1/leaves
          - /api/v1/leave-types
          - /api/v1/leave-balances
        strip_path: false
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          credentials: true
      - name: jwt
        config:
          claims_to_verify:
            - exp
      - name: rate-limiting
        config:
          minute: 100
          policy: local
      - name: prometheus

  # Payroll Service
  - name: payroll-service
    url: http://payroll-service-upstream
    protocol: http
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    routes:
      - name: payroll-routes
        paths:
          - /api/v1/payroll
        strip_path: false
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          credentials: true
      - name: jwt
        config:
          claims_to_verify:
            - exp
      - name: rate-limiting
        config:
          minute: 50
          policy: local
      - name: prometheus
      - name: request-size-limiting
        config:
          allowed_payload_size: 20

  # Notification Service
  - name: notification-service
    url: http://notification-service-upstream
    protocol: http
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    routes:
      - name: notification-routes
        paths:
          - /api/v1/notifications
        strip_path: false
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          credentials: true
      - name: jwt
        config:
          claims_to_verify:
            - exp
      - name: rate-limiting
        config:
          minute: 150
          policy: local
      - name: prometheus

# ==========================================
# Global Plugins
# ==========================================

plugins:
  - name: correlation-id
    config:
      header_name: X-Correlation-ID
      generator: uuid
      echo_downstream: true

  - name: request-id
    config:
      header_name: X-Request-ID
      generator: uuid
      echo_downstream: true

  - name: response-ratelimiting
    config:
      limits:
        video:
          minute: 10
        image:
          minute: 100
