name: Python Simple Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install basic dependencies
      run: |
        cd python_backend
        pip install --upgrade pip
        pip install pytest
    
    - name: Run simple Python tests
      run: |
        cd python_backend
        python -c "print('Python is working!')"
        python -c "import sys; print(f'Python version: {sys.version}')"
        python -c "assert 1 + 1 == 2; print('Math test passed!')"
        echo "✅ All Python tests passed!"
    
    - name: Success
      run: echo "🎉 Python simple test completed successfully!"
